# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

# Schemes
# scheme: Muse
# scheme: Mist
# scheme: Pisces
scheme: Gemini

# ä¾§è¾¹æ å¤´åƒè®¾ç½®
avatar:
  url: /images/avatar.jpg
  # å¦‚æœä½ æƒ³è®©å¤´åƒå˜åœ†ï¼Œå°±æŠŠè¿™ä¸ªè®¾ä¸º true
  rounded: true
  # å¦‚æœä½ æƒ³è®©å¤´åƒæ—‹è½¬ï¼ˆé¼ æ ‡æ”¾ä¸Šå»æ—¶ï¼‰ï¼Œè®¾ä¸º true
  rotated: false

custom_file_path:
  # head: source/_data/head.swig
  # header: source/_data/header.swig
  # sidebar: source/_data/sidebar.swig
  # postMeta: source/_data/post-meta.swig
  # postBody: source/_data/post-body.swig
  # footer: source/_data/footer.swig
  # bodyEnd: source/_data/body-end.swig
  
  # ğŸ‘‡ è§£å¼€è¿™ä¸€è¡Œï¼
  style: source/_data/styles.styl