# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

# Schemes
# scheme: Muse
# scheme: Mist
# scheme: Pisces
scheme: Gemini

# 侧边栏头像设置
avatar:
  url: /images/avatar.jpg
  # 如果你想让头像变圆，就把这个设为 true
  rounded: true
  # 如果你想让头像旋转（鼠标放上去时），设为 true
  rotated: false

custom_file_path:
  # head: source/_data/head.swig
  # header: source/_data/header.swig
  # sidebar: source/_data/sidebar.swig
  # postMeta: source/_data/post-meta.swig
  # postBody: source/_data/post-body.swig
  # footer: source/_data/footer.swig
  # bodyEnd: source/_data/body-end.swig
  
  style: source/_data/styles.styl

menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags  
  categories: /categories/ || fa fa-th 
  archives: /archives/ || fa fa-archive

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1

# pjax: true

creative_commons:
  license: by-nc-sa
  sidebar: true
  post: true

busuanzi_count:
  # 开启开关
  enable: true
  
  # 统计全站访客数 (UV) - 也就是有多少人来过
  total_visitors: true
  total_visitors_icon: fa fa-user
  
  # 统计全站总访问量 (PV) - 也就是页面被刷了多少次
  total_views: true
  total_views_icon: fa fa-eye
  
  # 统计单篇文章阅读量 (在文章标题下面显示)
  post_views: true
  post_views_icon: fa fa-eye

social:
  # 格式：名字: 链接 || 图标代码
  GitHub: https://github.com/CatIsTrue || fab fa-github
  Zhihu: https://www.zhihu.com/people/dan-gao-gong-zhu || fab fa-zhihu


social_icons:
  enable: true
  icons_only: false       # 是否只显示图标，不显示文字
  transition: false       # 是否开启悬停动画

# Reward (Donate)
reward_settings:
  # 如果设为 true，默认每篇文章都会显示打赏按钮
  enable: true
  animation: false
  # 按钮上的文字
  comment: 江湖卖艺，有钱的捧个钱场，有人的捧个人场：P

reward:
  # 格式：名字: 图片链接
  wechatpay: /images/wechatpay.png
  # alipay: /images/alipay.png
  # paypal: /images/paypal.png

# next 不支持 waline
# 1. 确保评论系统激活
# comments:
#   active: waline
#   # ...其他保持默认

# # 2. 填入你的 Vercel 地址
# waline:
#   enable: true
#   serverURL: https://waline-comment-blond-rho.vercel.app  # <--- 这里填你刚才拿到的地址
#   placeholder: 请文明评论，留下你的足迹~
#   avatar: mm # 默认头像风格
#   pageSize: 10
#   visitor: true # 阅读量统计
#   comment_count: true # 评论数统计